### ISSUE TITLE
It's better to choose rest api instead of the current one.

### ISSUE THREAD

**Issue by lian1925** [PX-hunter/Pingan_FE_Official#2]
I think rest api is concise and easy to understand. 

For example:
Get /api/blog/detail?id=xxx     =>    Get api/blog/{id}
Post /api/blog/update              =>    Put api/blog/{id}
Post /api/blog/del                    =>     Delet api/blog/{id}

**Comment by PX-hunter** [comment]
suggestion accepted :)

**Comment by lian1925** [comment]
well done. @PX-hunter
